version: "3.8"
services:
  backend_service:
    image: javalon007/test-repo:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    volumes:
      - /backend/node_modules

  frontend_service:
    image: javalon007/test-frontend-app:latest
    environment:
      - API_URL=backend_service:5000
    ports:
      - "3000:3000"
    volumes:
      - /frontend/node_modules
    depends_on:
      - backend_service
