version: "3"
services:
  app1:
    image: javalon007/test-repo:latest
    build:
      context: ./app1
      dockerfile: Dockerfile
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"

  app2:
    image: javalon007/test-repo:latest
    build:
      context: ./app2
      dockerfile: Dockerfile
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"

  app3:
    image: javalon007/test-repo:latest
    build:
      context: ./app2
      dockerfile: Dockerfile
    environment:
      - APP_NAME=App3
    ports:
      - "3003:3000"
