version: "3.8"
services:
  backend_service:
    image: javalon007/test-repo:${BACKEND_TAG}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    volumes:
      - /backend/node_modules
    networks:
      - test_network

networks:
  test_network:
    external: true
