version: "3.8"
services:
  frontend_service:
    image: javalon007/test-frontend-app:${FRONTEND_TAG}
    ports:
      - "3000:3000"
    volumes:
      - /frontend/node_modules
    depends_on:
      - backend_service
    networks:
      - test_network

  nginx_rp_gateway:
    image: nginx:1.16.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf:/etc/nginx/conf.d/
      - ./certs:/etc/nginx/certs/
    depends_on:
      - frontend_service
      - backend_service
    networks:
      - test_network

networks:
  test_network:
    external: true
