version: "3"
services:
  app1:
    build: javalon007/test-repo:latest
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"

  app2:
    build: javalon007/test-repo:latest
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"

  app3:
    build: javalon007/test-repo:latest
    environment:
      - APP_NAME=App3
    ports:
      - "3003:3000"
