name: Deploy Backend Service Infra

on:
  repository_dispatch:
    types: [deploy-backend-app]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.commit.outputs.SHORT_SHA }}

    steps:
      - name: set vars from dispatch
        id: vars
        run: |
          echo "REPO=${{github.event.client_payload.source_repo}}" >> $GITHUB_ENV

      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          repository: ezechuka/${{ env.REPO }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: main

      - name: Get commit SHA
        id: commit
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO }}:${{ steps.commit.outputs.SHORT_SHA }} \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO }}:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO }}:${{ steps.commit.outputs.SHORT_SHA }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO }}:latest

  deploy:
    name: Deploy to Docker Swarm with Stack
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set image tag in compose file
        run: |
          TAG=${{ needs.build-and-push.outputs.commit_sha }}
          sed -i "s/\${BACKEND_TAG}/$TAG/g" docker-compose.backend.yml

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Upload compose file to VPS
        run: |
          scp docker-compose.backend.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/app/${{ secrets.DEPLOY_USER }}/docker-compose.backend.yml

      - name: SSH into VPS and update backend service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            scp docker-compose.backend.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/app/${{ secrets.DEPLOY_USER }}/docker-compose.backend.yml
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO }}:${{ needs.build-and-push.outputs.commit_sha }} mystack_backend_service || \
            docker stack deploy -c /app/${{ secrets.DEPLOY_USER }}/docker-compose.backend.yml mystack
