name: Deploy Service Infra

on:
  repository_dispatch:
    types: [deploy-app]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: set vars from dispatch
        id: vars
        run: |
          echo "REPO=${{github.event.client_payload.source_repo}}" >> $GITHUB_ENV

      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          repository: ezechuka/${{ env.REPO }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: main

      - name: Get commit SHA
        id: commit
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "latest, ${{ steps.commit.outputs.SHORT_SHA }}"
# - name: Build Docker Image
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/${{env.REPO}}:${{ steps.commit.outputs.SHORT_SHA }} \
#           -t ${{ secrets.DOCKER_USERNAME }}/${{env.REPO}}:latest .

# - name: Push Docker Image
#         run: |
#           docker push ${{ secrets.DOCKER_USERNAME }}/${{env.REPO}}:${{ steps.commit.outputs.SHORT_SHA }}
#           docker push ${{ secrets.DOCKER_USERNAME }}/${{env.REPO}}:latest
