name: Deploy Frontend Service Infra

on:
  repository_dispatch:
    types: [deploy-frontend-app]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.commit.outputs.SHORT_SHA }}

    steps:
      - name: set vars from dispatch
        id: vars
        run: |
          echo "REPO=${{github.event.client_payload.source_repo}}" >> $GITHUB_ENV

      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          repository: ezechuka/${{ env.REPO }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: main

      - name: Get commit SHA
        id: commit
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO }}:${{ steps.commit.outputs.SHORT_SHA }} \
          -t ${{ secrets.DOCKER_USERNAME }}/${{env.REPO}}:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO }}:${{ steps.commit.outputs.SHORT_SHA }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO }}:latest

  deploy:
    name: Deploy to Docker Swarm with Stack
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set image tag in compose file
        run: |
          TAG=${{ needs.build-and-push.outputs.commit_sha }}
          sed -i "s/\${FRONTEND_TAG}/$TAG/g" docker-compose.yml
          sed -i "s/\${BACKEND_TAG}/latest/g" docker-compose.yml

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure remote folder exists
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "mkdir -p /app/${{ secrets.DEPLOY_USER }}"

      - name: Upload compose file to VPS
        run: |
          scp -r conf ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/app/${{ secrets.DEPLOY_USER }}
          scp docker-compose.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/app/${{ secrets.DEPLOY_USER }}/docker-compose.yml

      - name: Deploy via SSH with Docker Stack
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            docker stack deploy -c /app/${{ secrets.DEPLOY_USER }}/docker-compose.yml mystack
          EOF
